version: "3.7"
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

    # first load the 'db' service
    depends_on:
    - db
    links:
      - db

  db:
      image: mysql:5.7
      restart: always
      ports:
      - "13306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: jjgym_calendar
      volumes:
      - ./mysql:/var/lib/mysql
